/**
 * Build-time: read `config/tongflow.abi.json` → write `src/generated/abi/index.ts`.
 * Run via: pnpm gen:abi
 */

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { MIN_SUPPORTED_ABI_VERSION } from "../src/lib/schema/abi-version";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.join(__dirname, "..");
const abiPath = path.join(repoRoot, "config", "tongflow.abi.json");
const outDir = path.join(repoRoot, "src", "generated", "abi");
const outPath = path.join(outDir, "index.ts");

type AbiFile = {
    version: number;
    $defs?: Record<string, unknown>;
    nodes: Array<{ nodeSlot: string; inputs: unknown; outputs: unknown }>;
};

function readAbi(): AbiFile {
    const raw = fs.readFileSync(abiPath, "utf8");
    const data = JSON.parse(raw) as AbiFile;
    if (
        typeof data.version !== "number" ||
        !Number.isInteger(data.version) ||
        data.version < MIN_SUPPORTED_ABI_VERSION
    ) {
        console.error(
            `gen-abi-types: ABI version must be integer >= ${MIN_SUPPORTED_ABI_VERSION}, got ${JSON.stringify(data.version)}`,
        );
        process.exit(1);
    }
    if (!Array.isArray(data.nodes) || data.nodes.length === 0) {
        console.error("gen-abi-types: ABI nodes[] missing or empty");
        process.exit(1);
    }
    for (let i = 0; i < data.nodes.length; i++) {
        const n = data.nodes[i];
        if (!n || typeof n.nodeSlot !== "string" || n.nodeSlot.length === 0) {
            console.error(
                `gen-abi-types: nodes[${i}] missing or invalid nodeSlot`,
            );
            process.exit(1);
        }
    }
    return data;
}

function slotSafeId(slot: string): string {
    return slot.replace(/[^a-zA-Z0-9_]/g, "_");
}

/** Split on underscores and hyphens; capitalize segments (JSON Schema keywords stay lowercase → treat as identifiers). */
function slotToPascalBase(slot: string): string {
    const parts = slot.split(/[-_]/).filter(Boolean);
    if (parts.length === 0) return "Unknown";
    return parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join("");
}

/** Walk schema and resolve `#/$defs/*` refs to copies from `defs` (for FromSchema inference). Keep when ABI uses `$ref` on slots; refs still compile at runtime via `ABI_DEFINITIONS`. */
function inlineRefs(schema: unknown, defs: Record<string, unknown>): unknown {
    if (schema === null || typeof schema !== "object") return schema;
    if (Array.isArray(schema)) {
        return schema.map((item) => inlineRefs(item, defs));
    }
    const o = schema as Record<string, unknown>;
    if (typeof o.$ref === "string") {
        const ref = o.$ref;
        if (ref.startsWith("#/$defs/")) {
            const name = ref.slice("#/$defs/".length);
            const resolved = defs[name];
            if (resolved !== undefined) {
                return inlineRefs(
                    JSON.parse(JSON.stringify(resolved)) as unknown,
                    defs,
                );
            }
        }
    }
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(o)) {
        out[k] = inlineRefs(v, defs);
    }
    return out;
}

/** Build exported type basename per slot (disambiguate rare Pascal clashes). */
function buildSlotBaseTypes(slots: string[]): Map<string, string> {
    const pascalCount = new Map<string, number>();
    for (const s of slots) {
        const p = slotToPascalBase(s);
        pascalCount.set(p, (pascalCount.get(p) ?? 0) + 1);
    }
    const map = new Map<string, string>();
    for (const s of slots) {
        let base = slotToPascalBase(s);
        if ((pascalCount.get(base) ?? 0) > 1) base = `${base}_${slotSafeId(s)}`;
        map.set(s, base);
    }
    return map;
}

/** JSON snippet safe to append ` as const` for json-schema-to-ts */
function stringifySchema(obj: unknown): string {
    return JSON.stringify(obj, null, 4);
}

function generateTs(abi: AbiFile): string {
    const defs = abi.$defs ?? {};
    const lines: string[] = [];

    lines.push(
        "/** Generated by scripts/gen-abi-types.ts — do not edit manually. */",
    );
    lines.push("/** Run: `pnpm gen:abi` */");
    lines.push("");
    lines.push('import type { FromSchema } from "json-schema-to-ts";');
    lines.push('import type { JSONSchema7 } from "json-schema";');
    lines.push("");

    if (defs.Asset === undefined) {
        throw new Error("gen-abi-types: ABI missing $defs.Asset");
    }

    const inlinedAsset = inlineRefs(defs.Asset, defs);
    lines.push("// --- Asset ($refs inlined for FromSchema only) ---");
    lines.push(
        `const _AbiAssetSchemaInline = ${stringifySchema(inlinedAsset)} as const;`,
    );
    lines.push("export type Asset = FromSchema<typeof _AbiAssetSchemaInline>;");
    lines.push("");

    const slotOrder = abi.nodes.map((n) => n.nodeSlot);
    const seen = new Set<string>();
    for (const s of slotOrder) {
        if (seen.has(s)) {
            throw new Error(
                `gen-abi-types: duplicate nodeSlot ${JSON.stringify(s)}`,
            );
        }
        seen.add(s);
    }

    const slotBaseTypes = buildSlotBaseTypes(slotOrder);

    lines.push(
        "// --- Per-slot I/O types (schemas inlined only for inference) ---",
    );
    for (const n of abi.nodes) {
        const sid = slotSafeId(n.nodeSlot);
        const typeBase = slotBaseTypes.get(n.nodeSlot) ?? "";
        const inlinedIn = inlineRefs(n.inputs, defs);
        const inlinedOut = inlineRefs(n.outputs, defs);
        lines.push(
            `const _slot_${sid}_inputs = ${stringifySchema(inlinedIn)} as const;`,
        );
        lines.push(
            `export type ${typeBase}Input = FromSchema<typeof _slot_${sid}_inputs>;`,
        );
        lines.push(
            `const _slot_${sid}_outputs = ${stringifySchema(inlinedOut)} as const;`,
        );
        lines.push(
            `export type ${typeBase}Output = FromSchema<typeof _slot_${sid}_outputs>;`,
        );
        lines.push("");
    }

    const nodeSlots = abi.nodes
        .map((n) => JSON.stringify(n.nodeSlot))
        .join("\n\t| ");
    lines.push("// --- NodeSlot union ---");
    lines.push(`export type NodeSlot =\n\t| ${nodeSlots};`);

    lines.push("");
    lines.push("// --- Lookup maps ---");
    lines.push("export type SlotInputsMap = {");
    for (const n of abi.nodes) {
        const tb = slotBaseTypes.get(n.nodeSlot) ?? "";
        lines.push(`\t${JSON.stringify(n.nodeSlot)}: ${tb}Input;`);
    }
    lines.push("}");
    lines.push("");
    lines.push("export type SlotOutputsMap = {");
    for (const n of abi.nodes) {
        const tb = slotBaseTypes.get(n.nodeSlot) ?? "";
        lines.push(`\t${JSON.stringify(n.nodeSlot)}: ${tb}Output;`);
    }
    lines.push("}");
    lines.push("");
    lines.push("export type SlotInput<S extends NodeSlot> = SlotInputsMap[S];");
    lines.push(
        "export type SlotOutput<S extends NodeSlot> = SlotOutputsMap[S];",
    );

    const abiRuntime: Record<string, { inputs: unknown; outputs: unknown }> =
        {};
    for (const n of abi.nodes) {
        abiRuntime[n.nodeSlot] = {
            inputs: n.inputs as unknown,
            outputs: n.outputs as unknown,
        };
    }

    lines.push("");
    lines.push(
        "// --- Runtime ABI: keep per-node schemas as-is and expose $defs so AJV can resolve #/$defs/* ---",
    );
    lines.push("export type AbiNodeSchemas = {");
    lines.push("\treadonly inputs: JSONSchema7;");
    lines.push("\treadonly outputs: JSONSchema7;");
    lines.push("};");
    lines.push("");
    const defsJson = JSON.stringify(defs, null, "\t");
    lines.push(
        "// Pass as root `$defs` (or AJV equivalently); merge with `{ ...inputsSchema }` when validating",
    );
    // Use `as` casts (not type annotations) so JSON Schema extension keywords
    // like `x-expand-each` don't trip TS excess-property checks on the literals.
    lines.push(
        `export const ABI_DEFINITIONS = ${defsJson} as unknown as Record<string, JSONSchema7>;`,
    );
    lines.push("");
    lines.push(
        `export const ABI_NODES = ${JSON.stringify(abiRuntime, null, "\t")} as unknown as Record<NodeSlot, AbiNodeSchemas>;`,
    );

    return `${lines.join("\n")}\n`;
}

try {
    const abi = readAbi();
    const ts = generateTs(abi);
    fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(outPath, ts, "utf8");
    const rel = path.relative(repoRoot, outPath);
    const biomeBin = path.join(
        repoRoot,
        "node_modules",
        ".bin",
        process.platform === "win32" ? "biome.cmd" : "biome",
    );
    const fmt = spawnSync(biomeBin, ["check", "--write", rel], {
        cwd: repoRoot,
        stdio: "inherit",
        shell: process.platform === "win32",
    });
    if (fmt.status !== 0) {
        throw new Error(`biome check --write failed for ${rel}`);
    }
    console.log(`Wrote ${rel}`);

    // Bundle the ABI with the Python SDK so a pip-installed `tongflow` can run
    // workflows standalone (tongflow.engine reads it via abi_schema). Keeping
    // the copy in this step prevents the bundled ABI from drifting.
    const sdkAbiDir = path.join(repoRoot, "sdk", "tongflow", "_data");
    const sdkAbiPath = path.join(sdkAbiDir, "tongflow.abi.json");
    fs.mkdirSync(sdkAbiDir, { recursive: true });
    fs.copyFileSync(abiPath, sdkAbiPath);
    console.log(`Wrote ${path.relative(repoRoot, sdkAbiPath)}`);
} catch (e) {
    console.error("gen-abi-types failed:", e);
    process.exit(1);
}
